version: '3'
services:
  alfresco:
    build:
      context: ./alfresco
      args:
        ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
    mem_limit: 1700m
    environment:
      JAVA_OPTS: "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.secureComms=none
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=127.0.0.1
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Ddeployment.method=DOCKER_COMPOSE
        -Dmessaging.subsystem.autoStart=false
        -Dauthentication.protection.enabled=false
        -Dcsrf.filter.enabled=false
        -Dalfresco.restApi.basicAuthScheme=true
        -Xms1500m -Xmx1500m
        "
    networks:
      - mybridge
  mysql:
    build:
      context: ./
      dockerfile: DockerfileMysql
    container_name: "mysql"
    environment:
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - mybridge
  connectors:
    build:
      dockerfile: DockerfileUAlfresco
    container_name: connectors
    networks:
      - mybridge
    depends_on:
      - alfresco
      - mysql
    command: ["java", "-jar", "connector.jar"]


networks:
  mybridge:
    driver: bridge
  camunda-platform:
volumes:
  common:
  zeebe:
  elastic: